### ISSUE TITLE
`elastic` plugin with `elastic_security_cases` data source

### ISSUE THREAD

**Issue by traut** [blackstork-io/fabric#112]
### Description
[Cases objects](https://www.elastic.co/guide/en/security/current/cases-overview.html) are not exposed through Elasticsearch API for security reasons, making it impossible to query / search cases using search-based `elasticsearch` data source. A dedicated data source is required.

### Use Case
Elastic SIEM Cases data source will allow users to fetch and utilize information about ongoing and past security cases.

### Requirements

- configuration:
    - `kibana_endpoint_url` - (required) string argument, for example `https://custom-cluster.kb.us-central1.gcp.cloud.es.io:9243`
    - `api_key_str` - (optional) string argument (similar to https://github.com/blackstork-io/fabric/issues/19)
    - `api_key` - (optional) list of 2 strings
- parameters
    - support all path / query parameters listed in [the documentation](https://www.elastic.co/guide/en/kibana/8.12/cases-api-find-cases.html) apart from the pagination parameters. 
    - `size` - (optional) int argument, default value: 10.

#### Behavior

The requests are performed against `/api/cases/_find` or `/s/<space_id>/api/cases/_find` endpoint ([see the docs](https://www.elastic.co/guide/en/kibana/8.12/cases-api-find-cases.html)).

The API key must be set in the `Authorization` header as `ApiKey <key>`, where `<key>` is a base64-encoded `<key_id>:<key_value>` (if `api_key` attribute is set and contains 2 values) or `<api_key_str>`.

The data source must return a list of cases (joined from multiple responses if the pagination is happening)

Example:
```bash
$ http get https://my-cluster.kb.us-central1.gcp.cloud.es.io:9243/api/cases/_find Authorization:"ApiKey c29tZWtleWlkOnNvbWVrZXl2YWx1ZQ=="
HTTP/2 200
accept-ranges: bytes
...

{
    "page": 1,
    "per_page": 20,
    "total": 1,
    "cases": [
        {
            "title": "Test Case 1",
            "tags": [],
            "description": "test",
            "assignees": [
                {
                    "uid": "u_S_CT8Q42KR4061813M3VPXOASM2VY1P3TVMYDNY1EEB_0"
                }
            ],
            "settings": {
                "syncAlerts": true
            },
            "owner": "securitySolution",
            "connector": {
                "id": "none",
                "type": ".none",
                "fields": null,
                "name": "none"
            },
            "severity": "low",
            "status": "open",
            "category": null,
            "customFields": [],
            "duration": null,
            "closed_at": null,
            "closed_by": null,
            "created_at": "2023-04-22T05:11:05.054Z",
            "created_by": {
                "username": "sergey@blackstork.io",
                "full_name": null,
                "email": null,
                "profile_uid": "u_S_8CF0I28KMQJXIQ5CMOQ5NV65HEFZIETBIKHVV30IR_0"
            },
            "updated_at": null,
            "updated_by": null,
            "external_service": null,
            "id": "dcb62305-2ef7-4ccc-8b0b-d8314f4c6a52",
            "version": "WzIzNzkzNDc2LDExXQ==",
            "totalComment": 0,
            "totalAlerts": 0,
            "comments": [ ]
        }
    ],
    "count_open_cases": 1,
    "count_in_progress_cases": 0,
    "count_closed_cases": 0
}
```

### Additional Information
- Cases API ["Find Cases" docs](https://www.elastic.co/guide/en/kibana/8.12/cases-api-find-cases.html)

**Comment by traut** [comment]
@dobarx I suggest we make a new `elastic` plugin (instead of existing `elasticsearch` one) and mode `elasticsearch` data source there.

**Comment by dobarx** [comment]
So one `blackstork/elastic` plugin with these two data sources?

- `elasticsearch`
- `elastic_security_cases`

It feels like it should be `elastic_search` for consistency but I know that it's most commonly named as one word `elasticsearch`. 
Also on the same topic, we should enforce a rule that all data sources and content providers of a plugin should start with plugin name prefix.

**Comment by traut** [comment]
oh, indeed, `security_cases` is too generic to be used -- it is unclear that it is related to Elastic SIEM!

Lets make `blackstork/elastic` plugin with 
- `elasticsearch`
- `elastic_security_cases`

It does fit the correct names of the products: "Elasticsearch" and "Elastic Security". 

> Also on the same topic, we should enforce a rule that all data sources and content providers of a plugin should start with plugin name prefix. It makes easier to know which plugin owns this data source/content provider and allows to avoid collisions.

This is a good point. I suggest we wait a bit with the constraint though until we start creating more data sources / content providers per plugin and see how it shapes.

**Comment by traut** [comment]
another note: similar to https://github.com/blackstork-io/fabric/issues/113 , this plugin must have `only_cases` boolean argument (`true` by default).

If `only_cases` is set to `true`, a list of cases objects is returned. If `only_cases` set to `false`, the raw response is returned.

> [!WARNING]
> There can be multiple raw responses if the pagination is required (`size` value is higher than max page size). In this case, the plugin should throw an error
