### ISSUE TITLE
Add `rows_var` attribute to `content.table` content provider

### ISSUE THREAD

**Issue by traut** [blackstork-io/fabric#169]
### Description
Currently, `content.table` relies on `query` to return an iterable collection for the table rows. This is implicit non-obvious behavior.

### Design
Introduce `rows_var` attribute for `content.table` content provider as an explicit input data for rendering.

`rows_var` must define a collection of items (either as a static value or as the result of the data transformation).

Example:
```hcl

data inline test_data {
    test_value = "xxx"
}

content table "my_table" {
  vars {
    some_value = query_jq(".data.inline.text_data.test_value")
  }

  rows_var = <<-EOT
     ["aaa", "bbb", "ccc", .vars.some_value]
  EOT

  columns = [
    { header = "Value", value = "{{ .vars.row }}"},
    { header = "Index", value = "{{ .vars.row_index }}"},
    { header = "ValueFromContext {{ .vars.some_value }}", value = "{{ .vars.some_value }}"},
    { header = "StaticValue", value = "foo"},
  ]
}
```
will render into
```markdown
| Value | Index | ValueFromContext xxx | StaticValue |
|-------|-------|----------------------|-------------|
| aaa   | 0     | xxx                  | foo         |
| bbb   | 1     | xxx                  | foo         |
| ccc   | 2     | xxx                  | foo         |
| xxx   | 3     | xxx                  | foo         |
```

### Provider-specific variables

The content provider sets these variables in the context for every row:
- `.vars.rows` -- the value of `rows_var` attribute
- `.vars.row` -- the current item from `.vars.rows` collection
- `.vars.row_index` -- the current item index 

> [!WARNING]
> Since `rows_var` is specific to `content.table` content provider, it must be evaluated after a generic `vars` block is evaluated (if present)

## References 
- https://github.com/blackstork-io/fabric/issues/166
- https://gist.github.com/traut/029ce180869364891d176307de8ea06e

**Comment by Andrew-Morozko** [comment]
> introduce row_index variable

Are we ignoring the possibility of `row_index` being already present in the user's data? Perhaps we should prefix our variables (`fabric_row_index`) to try to avoid collisions, or we may go even further by creating a `row_index()` function that has no chance of shadowing user's data

**Comment by traut** [comment]
> Can we clarify something here? ["aaa", "bbb", "ccc"] returns one result, it being the list ["aaa", "bbb", "ccc"]. But jq supports returning multiple results, for example ["aaa", "bbb", "ccc"][] would return the 3 strings as 3 separate results. You have better knowlege of how jq feels, which is the better user experience?

that's a good question. I don't have a clear answer here -- we need to look into how `[]` vs separate results are represented by `gojq`. On the code level, I would expect `rows_var` here to return a collection that can be iterated over.

**Comment by traut** [comment]
Oh, I just realized that the `content.list` provider suffers from the same issue — it uses `.query_result` implicitly. 

I believe it should be adjusted to support with `items_var` attribute (similar to `rows_var` for the tables)

**Comment by Andrew-Morozko** [comment]
> `content.list` provider suffers from the same issue — it uses `.query_result` implicitly.

`frontmatter` and `stixview` also use "query_result"

**Comment by traut** [comment]
more things to adjust. would you like to split that work into a separate issue?

**Comment by Andrew-Morozko** [comment]
Was just about to propose that. Vars PR is ready and tested, except it doesn't remove `query`, `.query_result`, and `data inline`.

Quick regexp over the codebase shows that there are 100-200 distinct places where we reference those strings, so it will be a lot of work if we want to do it all at once.

**Comment by traut** [comment]
gotcha, will make a separate issue for other occurrences. thanks!

**Comment by traut** [comment]
to follow up on our discussion @Andrew-Morozko

- it makes sense to add a "required vars" specification for content blocks, the same way https://github.com/blackstork-io/fabric/issues/29 defines it -- the content provider should be able to set that property
- for `content.table` (and `content.list`), a content provider would expect to see `.vars.collection` to be set

**Comment by traut** [comment]
to follow up on our discussion @Andrew-Morozko

- it makes sense to add a "required vars" specification for content blocks, the same way https://github.com/blackstork-io/fabric/issues/29 defines it -- the content provider should be able to set that property
- for `content.table` (and `content.list`), a content provider would expect to see `.vars.collection` to be set

**Comment by Andrew-Morozko** [comment]
Finally implemented row vars. Here's the implementation, including changes discussed on slack.

```hcl
document "test" {
    vars {
        a = 1
        b = query_jq(".vars.a + 1")
        xxx = "xxx"
    }
    content table {
        rows_var = query_jq("[10, 20, 10*(.vars.b + 1)]")

        columns = [
            { header = "{{ .block.col_index }} Value", value = "{{ .block.row }}"},
            { header = "{{ .block.col_index }} Index", value = "{{ .block.row_index }}"},
            { header = "{{ .block.col_index }} ValueFromContext {{ .vars.xxx }}", value = "{{ .vars.xxx }}"},
            { header = "{{ .block.col_index }} StaticValue", value = "foo"},
        ]
    }
}
```
Result:
```md
|1 Value|2 Index|3 ValueFromContext xxx|4 StaticValue|
|---|---|---|---|
|10|1|xxx|foo|
|20|2|xxx|foo|
|30|3|xxx|foo|
```
