### ISSUE TITLE
Meta blocks on data source blocks are useless

### ISSUE THREAD

**Issue by Andrew-Morozko** [blackstork-io/fabric#95]
Data sources do not receive the context map, and nothing else in our system accesses meta blocks. What to do about it?

**Comment by traut** [comment]
It is alright for now! Currently, the `meta` blocks are used to provide the details about the template / block itself (like author, update time, etc), without affecting the block execution.

For non-data blocks, it will change -- we will be using `meta.tags` values for filtering `document`/`section`/`content` blocks (https://github.com/blackstork-io/fabric/issues/99)

For data blocks, we will see how the meta data can be used!
